# @package _global_

defaults:
  - /habitat: habitat_config_base
  # - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_head_agent
  - /habitat/task: pointnav
  - /habitat/simulator/agents:
    - rgbds_agent
  - /habitat/dataset/pointnav: mp3d
  - _self_

habitat:
  # gym:
  #   auto_name: Pick
  #   obs_keys:
  #     - robot_head_depth
  #     - obj_start_sensor
  #     - joint
  #     - is_holding
  #     - relative_resting_position
  environment:
    max_episode_steps: 10
    # iterator_options/shuffle: false
  simulator:
    # type: PointNav-v1
    agents:
      rgbd_agent:
        sim_sensors:
          rgb_sensor:
            width: 128
            height: 128
          depth_sensor:
            width: 128
            height: 128
          semantic_sensor:
            width: 128
            height: 128
    # additional_object_paths:
    #   - data/objects/ycb/configs/
    # needs_markers: False
    # concur_render: True
    # auto_sleep: True
    # agents:
    #   main_agent:
    #     radius: 0.3
    #     robot_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
    #     robot_type: FetchSuctionRobot

    #  habitat_sim_v0:
    #   allow_sliding: False
    #   enable_physics: True

  dataset:
    data_path: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
