ENVIRONMENT:
  MAX_EPISODE_STEPS: 10
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR','SEMANTIC_SENSOR']
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
  SEMANTIC_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: /home/shen/habitat_data/myproject/habitat/SemanticAnticipation/data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
TASK:
  TYPE: Nav-v0
  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POSSIBLE_ACTIONS: ['STOP', 'MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'TELEPORT']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2